// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using JsonOrg;
using System;

namespace KiiCorp.Cloud.Storage
{
    /// <summary>
    /// Represents a result of server side code execution.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public class KiiServerCodeExecResult
    {
        private JsonObject result;
        private int execSteps;
        private KiiServerCodeEnvironmentVersion? environmentVersion;

        internal KiiServerCodeExecResult (JsonObject result, int execSteps, KiiServerCodeEnvironmentVersion? environmentVersion)
        {
            this.result = result;
            this.execSteps = execSteps;
            this.environmentVersion = environmentVersion;
        }

        #region Properties
        /// <summary>
        /// Gets the returned object.
        /// </summary>
        /// <remarks>
        /// This property does not return null.
        /// </remarks>
        /// <value>The returned object.</value>
        public JsonObject ReturnedValue
        {
            get
            {
                return result;
            }
        }

        /// <summary>
        /// Gets the executed steps.
        /// </summary>
        /// <remarks>
        /// No
        /// </remarks>
        /// <value>The executed steps.</value>
        public int ExecutedSteps
        {
            get
            {
                return execSteps;
            }
        }
        /// <summary>
        /// Gets the version of Node.js which the server code was executed.
        /// </summary>
        /// <value>The environment version.</value>
        public KiiServerCodeEnvironmentVersion? EnvironmentVersion
        {
            get
            {
                return environmentVersion;
            }
        }
        #endregion
    }
}

