// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;

namespace KiiCorp.Cloud.Storage
{
    [TestFixture()]
    public class TestKiiUser_RUD
    {
        private MockHttpClient client;

        [SetUp()]
        public void SetUp()
        {
            Kii.Initialize("appId", "appKey", Kii.Site.US);
            MockHttpClientFactory factory = new MockHttpClientFactory();
            Kii.HttpClientFactory = factory;
            
            client = (MockHttpClient)factory.Client;
        }

        private void setStandardResponseForRefresh()
        {
            client.AddResponse(200, "{" +
                               "\"userID\" : \"userABCD\"," +
                               "\"internalUserID\" : 87442786592227328," +
                               "\"loginName\" : \"test001\"," +
                               "\"displayName\" : \"person test000\"," +
                               "\"country\" : \"JP\"," +
                               "\"emailAddress\" : \"test001@testkii.com\"," +
                               "\"emailAddressVerified\" : false," +
                               "\"phoneNumber\" : \"+819098439211\"," +
                               "\"phoneNumberVerified\" : true}");
        }

        private void LogIn()
        {
            // set Response
            client.AddResponse(200, "{" +
                               "\"id\" : \"user1234\"," +
                               "\"access_token\" : \"cdef\"," +
                               "\"expires_in\" : 9223372036854775}");
            KiiUser.LogIn("kii1234", "pass1234");
        }

        #region KiiUser.Refresh()

        [Test(), KiiUTInfo(
            action = "When we call Refresh() and Server returns KiiUser,",
            expected = "We can get UserID/DisplayName/Country/Email/EmailVerified/Phone/PhoneVerified that server sends"
            )]
        public void Test_0000_Refresh()
        {
            // set response
            this.setStandardResponseForRefresh();
            
            KiiUser user = KiiUser.CreateByUri(new Uri("kiicloud://users/abcd"));
            user.Refresh();
            Assert.AreEqual("abcd", user.ID);
            Assert.AreEqual("person test000", user.Displayname);
            Assert.AreEqual("JP", user.Country);
            Assert.AreEqual("test001@testkii.com", user.Email);
            Assert.AreEqual(false, user.EmailVerified);
            Assert.AreEqual("+819098439211", user.Phone);
            Assert.AreEqual(true, user.PhoneVerified);
        }
        
        [Test(), ExpectedException(typeof(InvalidOperationException)), KiiUTInfo(
            action = "When we call Refresh() to KiiUser that doesn't have UserID,",
            expected = "InvalidOperationException must be thrown"
            )]
        public void Test_0001_Refresh_null_id()
        {
            // set response
            this.setStandardResponseForRefresh();
            
            KiiUser user = KiiUser.BuilderWithName("kii1234").Build();
            user.Refresh();
        }
        
        [Test(), ExpectedException(typeof(CloudException)), KiiUTInfo(
            action = "When we call Refresh() and Server returns HTTP 400,",
            expected = "CloudException must be thrown"
            )]
        public void Test_0010_Refresh_server_error()
        {
            // set response
            client.AddResponse(new CloudException(400, "{}"));
            
            KiiUser user = KiiUser.CreateByUri(new Uri("kiicloud://users/abcd"));
            user.Refresh();
        }

        [Test(), ExpectedException(typeof(IllegalKiiBaseObjectFormatException)), KiiUTInfo(
            action = "When we call Refresh() and Server returns broken JSON,",
            expected = "IllegalKiiBaseObjectFormatException must be thrown"
            )]
        public void Test_0011_Refresh_broken_JSON()
        {
            // set response
            client.AddResponse(200, "broken");
            
            KiiUser user = KiiUser.CreateByUri(new Uri("kiicloud://users/abcd"));
            user.Refresh();
        }
        #endregion

        #region KiiUser.Update()

        [Test(), KiiUTInfo(
            action = "When we call Update() and Server returns HTTP 200,",
            expected = "user is updated"
            )]
        public void Test_0100_Update ()
        {
            this.LogIn();

            KiiUser user = KiiUser.CurrentUser;
            user["age"] = 29;

            // set response
            client.AddResponse(200, 
                    "{" +
                    "\"modifiedAt\" : 1386684079176" +
                    "}");

            user.Update();

            // Assertion
            Assert.AreEqual(29, user["age"]);
        }

        [Test(), ExpectedException(typeof(InvalidOperationException)), KiiUTInfo(
            action = "When we call Update() with other user,",
            expected = "InvalidOperationException is thrown"
            )]
        public void Test_0110_Update_other_user ()
        {
            this.LogIn();
            
            KiiUser user = KiiUser.CreateByUri(new Uri("kiicloud://users/1234"));
            user["age"] = 29;
            
            // set response
            client.AddResponse(200, 
                               "{" +
                               "\"modifiedAt\" : 1386684079176" +
                               "}");
            
            user.Update();
        }

        [Test(), ExpectedException(typeof(CloudException)), KiiUTInfo(
            action = "When we call Update() and Server returns HTTP 400,",
            expected = "CloudException is thrown"
            )]
        public void Test_0111_Update_Server_error ()
        {
            this.LogIn();
            
            KiiUser user = KiiUser.CurrentUser;
            user["age"] = 29;
            
            // set response
            client.AddResponse(new CloudException(400, "{}"));
            
            user.Update();
        }
        #endregion

        #region KiiUser.Delete()
        [Test(), KiiUTInfo(
            action = "When we call Delete() and Server returns HTTP 204,",
            expected = "No exception is thrown"
            )]
        public void Test_0200_Delete ()
        {
            this.LogIn();
            
            KiiUser user = KiiUser.CurrentUser;
            
            // set response
            client.AddResponse(204, ""); 
            
            user.Delete();

            // Assertion
            Assert.IsNull(KiiUser.CurrentUser);
        }

        [Test(), ExpectedException(typeof(CloudException)), KiiUTInfo(
            action = "When we call Delete() and Server returns HTTP 400,",
            expected = "CloudException is thrown"
            )]
        public void Test_0210_Delete_Server_error ()
        {
            this.LogIn();
            
            KiiUser user = KiiUser.CurrentUser;
            
            // set response
            client.AddResponse(new CloudException(400, "{}"));
            
            user.Delete();
        }
        #endregion
    }
}

