// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using System.Reflection;

namespace KiiCorp.Cloud.Storage
{
    [TestFixture()]
    public class TestSDKClientInfo
    {
        [Test()]
        public void TestCloudSDKInfo() {
            string sdkInfo = SDKClientInfo.GetSDKClientInfo();
            Assert.IsTrue(sdkInfo.StartsWith("sn=cs;sv="));
        }

        [Test()]
        public void TestSDKInfoIncludedInRequestHeader() {
            Kii.Initialize("appId", "appKey", Kii.Site.US);
            MockHttpClientFactory factory = new MockHttpClientFactory();
            Kii.HttpClientFactory = factory;
            
            // set response
            MockHttpClient client = factory.Client;
            client.AddResponse(200, "{\"objectID\": 1, \"createdAt\": 1}");
            
            string bucketName = "TestBucket";
            KiiBucket bucket = Kii.Bucket(bucketName);
            KiiObject obj = bucket.NewKiiObject();
            obj.Save();
            
            // check request.
            MockHttpHeaderList headerList = client.RequestHeader[0];
            Assert.AreEqual("appId",headerList["X-Kii-AppID"] );
            Assert.AreEqual("appKey",headerList["X-Kii-AppKey"] );
            string sdkInfo = headerList["X-Kii-SDK"];
            Assert.IsNotNull(sdkInfo);
            Assert.IsTrue(sdkInfo.StartsWith("sn=cs;sv="));
        }
    }
}

