// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace KiiCorp.Cloud.Analytics
{
    public class AnalyticsResultApp : BaseApp
    {
        const string APPID = "{APP ID}";
        const string APPKEY = "{APP KEY}";
        const string BASEURL = "http://api-jp.kii.com/api";

        public string AppId {
            get {
                return APPID;
            }
        }

        public string AppKey {
            get {
                return APPKEY;
            }
        }

        public string BaseUrl {
            get {
                return BASEURL;
            }
        }

        public string ClientId {
            get {
                throw new NotImplementedException ();
            }
        }

        public string ClientSecret {
            get {
                throw new NotImplementedException ();
            }
        }
    }
}

