// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace KiiCorp.Cloud.Storage
{
    public class TestApp : BaseApp
    {

        const string APP_ID = "{APP ID}";
        const string APP_KEY = "{APP KEY}";
        const string CLIENT_ID = "{CLIENT ID}";
        const string CLIENT_SECRET = "{CLIENT SECRET}";
        const string BASEURL = "http://api-jp.kii.com/api";

        public string AppId {
            get {
                return APP_ID;
            }
        }

        public string AppKey {
            get {
                return APP_KEY;
            }
        }

        public string BaseUrl {
            get {
                return BASEURL;
            }
        }

        public string ClientId {
            get {
                return CLIENT_ID;
            }
        }

        public string ClientSecret {
            get {
                return CLIENT_SECRET;
            }
        }
    }
}

