// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using JsonOrg;
using NUnit.Framework;
using System.Collections;

namespace KiiCorp.Cloud.Storage
{
    public class KiiAssertion
    {
        public static void AssertJson (JsonObject json1, JsonObject json2)
        {
            if (json1 == null || json2 == null) {
                Assert.IsTrue (json1 == json2);
                return;
            }
            Assert.IsTrue (JsonEquals (json1, json2));
        }

        private static Boolean JsonEquals (Object obj1, Object obj2)
        {
            if (obj1 is JsonObject && obj2 is JsonObject) {
                JsonObject json1 = (JsonObject)obj1;
                JsonObject json2 = (JsonObject)obj2;
                IEnumerator json1Keys = json1.Keys ();
                while (json1Keys.MoveNext()) {
                    string key = (string)json1Keys.Current;
                    if (!json2.Has (key))
                        return false;
                    Object value1 = json1.Get (key);
                    Object value2 = json2.Get (key);
                    if (! JsonEquals (value1, value2)){
                        return false;
                    }
                }
            } else if (obj1 is JsonArray && obj2 is JsonArray) {
                JsonArray obj1Array = (JsonArray)obj1;
                JsonArray obj2Array = (JsonArray)obj2;
                if (obj1Array.Length () != obj2Array.Length ())
                    return false;
                for (int i = 0; i < obj1Array.Length(); i++) {
                    Boolean matchFound = false;
                    for (int j = 0; j < obj2Array.Length(); j++) {
                        if (JsonEquals (obj1Array.Get (i), obj2Array.Get (j))) {
                            matchFound = true;
                            break;
                        }
                    }
                    if (!matchFound)
                        return false;
                }
            } else {
                return obj1.Equals (obj2);
            } 
            return true;
        }
    }
}
