// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using JsonOrg;

namespace KiiCorp.Cloud.Storage
{
  public class ApiHelper
  {

    public static string get(string url, string appId, string appKey, string token) 
    {
      KiiTestHttpClient client = new KiiTestHttpClientImpl(url, appId, appKey, KiiTestHttpMethod.GET);
      client.Headers["Authorization"] = "Bearer "+token;
      KiiTestHttpResponse response = client.SendRequest();
      return response.Body;
    }
  }
}

