// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace KiiCorp.Cloud.Storage
{
  public class SDKUtils
  {
    public static string GetObjectUFEUri(KiiObject obj) {
      Uri objUri = obj.Uri;
      return Utils.Path(Kii.BaseUrl,"apps", Kii.AppId, objUri.Authority , objUri.AbsolutePath);
    }

    public static string GetGroupUFEUri(KiiGroup group) {
      Uri groupUri = group.Uri;
      return Utils.Path(Kii.BaseUrl,"apps", Kii.AppId, groupUri.Authority , groupUri.AbsolutePath);
    }
  }
}

