// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using JsonOrg;

namespace KiiCorp.Cloud.Storage
{
    internal class APNSJsonMapper : JsonMapper
    {
        internal APNSJsonMapper(JsonObject json) : base(json)
        {
        }
        internal override string Origin {get{return this.json.OptString("o");}}
        internal override string Sender {get{return this.json.OptString("s");}}
        internal override string ObjectScopeType {get{return this.json.OptString("st");}}
        internal override string Topic {get{return this.json.OptString("to");}}
        internal override string ObjectScopeGroupID {get{return this.json.OptString("sg");}}
        internal override string ObjectScopeUserID {get{return this.json.OptString("su");}}
        internal override string BucketID {get{return this.json.OptString("bi");}}
        internal override string ObjectID {get{return this.json.OptString("oi");}}
        internal override string BucketType {get{return this.json.OptString("bt");}}
        internal override bool IsPushToAppMessage()
        {
            foreach (string requirementKey
                     in new string[] {
                "bi", // bucketID
                "bt", // bucketType
                "oi", // objectID
                "om"  // modifiedAt
            })
            {
                if (this.json.Has(requirementKey))
                {
                    return true;
                }
            }
            return false;
        }
        internal override bool IsPushToUserMessage()
        {
            return this.json.Has ("to");
        }
    }
}

