// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using JsonOrg;

namespace KiiCorp.Cloud.Storage
{
    internal class GCMJsonMapper : JsonMapper
    {
        internal GCMJsonMapper(JsonObject json) : base(json)
        {
        }
        internal override string Origin {get{return this.json.OptString("origin");}}
        internal override string Sender {get{return this.json.OptString("sender");}}
        internal override string ObjectScopeType {get{return this.json.OptString("objectScopeType");}}
        internal override string Topic {get{return this.json.OptString("topic");}}
        internal override string ObjectScopeGroupID {get{return this.json.OptString("objectScopeGroupID");}}
        internal override string ObjectScopeUserID {get{return this.json.OptString("objectScopeUserID");}}
        internal override string BucketID {get{return this.json.OptString("bucketID");}}
        internal override string ObjectID {get{return this.json.OptString("objectID");}}
        internal override string BucketType {get{return this.json.OptString("bucketType");}}
        internal override bool IsPushToAppMessage()
        {
            return ("EVENT".Equals(this.Origin)
                    || this.json.Has("bucketID")
                    || this.json.Has("bucketType"));
        }
        internal override bool IsPushToUserMessage()
        {
            return this.json.Has ("topic");
        }
    }
}

