// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
namespace KiiCorp.Cloud.Analytics
{
    [TestFixture()]
    public class TestSiteSG
    {

        [SetUp()]
        public void SetUp()
        {
            KiiAnalytics.Instance = null;
        }

        [TearDown()]
        public void TearDown()
        {
            KiiAnalytics.Instance = null;
        }

        [Test()]
        public void TestSite()
        {
            KiiAnalytics.Initialize("dummyAppId", "dummyAppKey", KiiAnalytics.Site.SG, "dummyDevieId");
            Assert.AreEqual("https://api-sg.kii.com/api", KiiAnalytics.BaseUrl);
        }

        [Test()]
        public void TestRequestUrl()
        {
            KiiAnalytics.Initialize("dummyAppId", "dummyAppKey", KiiAnalytics.Site.SG, "dummyDeviceId");
            MockHttpClientFactory factory = new MockHttpClientFactory();
            KiiAnalytics.HttpClientFactory = factory;
            KiiAnalytics.AsyncHttpClientFactory = factory;
            MockHttpClient client = (MockHttpClient)factory.Client;

            // send request
            client.AddResponse(200, "{" +
                               "\"snapshots\" : [ {" +
                               "\"name\" : \"Male\"," +
                               "\"data\" : [ 546.775207 ]," +
                               "\"pointStart\" : 1338044400000," +
                               "\"pointInterval\" : 86400000}]}");
            KiiAnalytics.GetResult("ruleId", null, null);

            // check request url.
            Assert.AreEqual("https://api-sg.kii.com/api/apps/dummyAppId/analytics/ruleId/data", client.RequestUrl[0]);
        }
    }
}

