// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace KiiCorp.Cloud.Storage
{
  /// <summary>
  /// The exception that is thrown when KiiCloud sends error response.
  /// </summary>
  /// <remarks>
  /// Developers can get server status code and body by properties.
  /// </remarks>
  public class KiiTestHttpException : SystemException
  {
    private int statusCode = -1;
    
    private string httpBody;
    
    internal KiiTestHttpException (int statusCode, string body)
    {
      this.statusCode = statusCode;
      this.httpBody = body;
    }
    
    internal KiiTestHttpException (int statusCode, string message, SystemException cause) : base(message, cause)
    {
      this.statusCode = statusCode;
      this.httpBody = "";
    }
    
    internal KiiTestHttpException (int statusCode, string message, SystemException cause, string httpBody) : base(message, cause)
    {
      this.statusCode = statusCode;
      this.httpBody = httpBody;
    }
    
    /// <summary>
    /// Dump http status and body. If the body is larger than 400 characters, It will be trimmed.
    /// </summary>
    /// <returns>A <see cref="System.String"/> that represents the current <see cref="KiiCorp.Cloud.Storage.CloudException"/>.</returns>
    public override string ToString ()
    {
      string bodyForPrinting = this.Body;
      if (bodyForPrinting != null && bodyForPrinting.Length > 400) {
        bodyForPrinting = this.Body.Substring(0,400) +"...truncated";
      }
      return string.Format ("[CloudException: Status={0} Body={1}]", this.Status, bodyForPrinting);
    }
    
    #region properties
    /// <summary>
    /// Gets the status code.
    /// </summary>
    /// <remarks>
    /// See the API documents.
    /// </remarks>
    /// <value>
    /// The status code.
    /// </value>
    public int Status
    {
      get
      {
        return statusCode;
      }
    }

    public string Body
    {
      get
      {
        return httpBody;
      }
    }
    #endregion
  }
}

