// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace KiiCorp.Cloud.Analytics
{

    /// <summary>
    /// This callback is used event list upload has completed.
    /// </summary>
    /// <remarks>
    /// <para>It is not guaranteed that this callback will be called on main thread.</para>
    /// <para>Please refer remark section of each API to know how to handle a response.</para>
    /// </remarks>
    /// <param name="e">
    /// The exception thrown in execution. If this value is null, execution is done successfully. 
    /// </param>
    public delegate void KiiEventCallback(Exception e);

    /// <summary>
    /// This callback is used analytics result has retrieved.
    /// </summary>
    /// <remarks>
    /// <para>It is not guaranteed that this callback will be called on main thread.</para>
    /// <para>Please refer remark section of each API to know how to handle a response.</para>
    /// </remarks>
    /// <param name='ruleId'>
    /// Specified rule identifier.
    /// </param>
    /// <param name='condition'>
    /// Specified result condition.
    /// </param>
    /// <param name='result'>
    /// Retrieved result.
    /// </param>
    /// <param name="e">
    /// The exception thrown in execution. If this value is null, execution is done successfully. 
    /// </param>
    public delegate void KiiResultCallback(string ruleId, ResultCondition condition, GroupedResult result, Exception e);
}

